FROM alpine
#ARG CODEBUILD_RESOLVED_SOURCE_VERSION
ARG BRANCH_CP
#RUN echo "CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION"
RUN echo "BRANCH_CP $BRANCH_CP"
#CMD echo "hogehoge" && echo "CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION" && sleep 600
CMD echo "hogehoge" && echo "BRANCH_CP $BRANCH_CP" && sleep 600
